version: "3.9"
services:
  docker_db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bicycle_fleet_data
    volumes:
      - docker_db_volume:/var/lib/mysql
  docker_server:
    build:
      context: ./server
    command: bash -c "alembic upgrade head && flask run --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/app/
    depends_on:
      - docker_db
    restart: always
  docker_client:
    build:
      context: ./client
    restart: always
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app/
      - /app/node_modules
    depends_on:
      - docker_server
volumes:
  docker_db_volume:

